name: Test
on: [push]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install imagemagick
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: bundle exec make test
